service: padel-checker

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.8
  region: ap-southeast-2
  timeout: 30 # optional, in seconds, default is 6
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 's3:*'
          Resource: '*'
  
package:
  exclude:
    - node_modules/**
    - venv/**

functions:
  check_padel_bookings:
    handler: checker.check_padel_bookings
    events:
      - schedule: cron(45 5 ? * MON-THU *)
      - schedule: cron(45 21 ? * FRI-SUN *)

custom:
  pythonRequirements:
    dockerizePip: true

plugins:
  - serverless-python-requirements
